name: Run CI checks # The name will show up on the GitHub Actions dashboard

on: [pull_request] # This workflow will run only on Pull Requests

jobs:
  install-deps:
    runs-on: ubuntu-latest
    name: Install Node Dependencies
    steps:
      - uses: actions/checkout@v2 # checkout whatever branch the PR is using
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    name: Building affected apps
    steps:
      - run: npm run nx affected -- --target=build --base=origin/master --parallel
  test:
    runs-on: ubuntu-latest
    needs: install-deps
    name: Testing affected apps
    steps:
      - run: npm run nx affected -- --target=test --base=origin/master --parallel
  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    name: Linting affected apps
    steps:
      - run: npm run nx affected -- --target=lint --base=origin/master --parallel
  e2e:
    runs-on: ubuntu-latest
    needs: install-deps
    name: E2E testing affected apps
    steps:
      - run: npm run nx affected -- --target=e2e --base=origin/master --parallel
